Orange Telecom's Churn
objective ----------> to predict weather a customer will churn or not
target variable ----> churn
problem ----------> classification  

Machine Learning model -------> Logistic Regression, SVM, Random Forest 
Deep Learning model ----------> ANN, RNN (LSTM), CNN

in CNN there is error which i don't understand and unable to find the solution for that ((( error is below listed )))
TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.layers.convolutional.Conv1D object at 0x000001EC49FA35F8>