Orange Telecom's Churn Dataset
The Orange Telecom's Churn Dataset, which consists of cleaned customer activity data (features), along with a churn label specifying whether a customer canceled the subscription,

objective -- to predict weather a customer will churn or not
target variable - churn
problem - classification   

machine learning model -------> logistic regression, SVM, random forest
deep learning model -----------> ANN, LSTM (RNN),

i used CNN but found some error -->
TypeError: The added layer must be an instance of class Layer. Found: <tensorflow.python.keras.layers.convolutional.Conv1D object at 0x000001EC49FA35F8>

--> unable to understand the error and solution